name: nt4
description: Dart implementation of the WPILib NT4 protocol
version: 1.3.3
repository: https://github.com/mjansen4857/nt4

environment:
  sdk: ^3.4.0

platforms:
  android:
  ios:
  linux:
  macos:
  windows:

dependencies:
  collection: ^1.18.0
  messagepack: ^0.2.1
  msgpack_dart: ^1.0.1
  web_socket_channel: ^3.0.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.5
  full_coverage: ^1.0.0
  coverage: ^1.8.0
