name: CI

on:
  push:
    branches: [main]
  
  pull_request:

  workflow_dispatch:

jobs:
  formatting:
    name: "Check Formatting"
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Setup dart
        uses: dart-lang/setup-dart@v1
      
      - name: Install dependencies
        run: dart pub get
      
      - name: Check formatting
        run: dart format -o none --set-exit-if-changed lib/* test/*
  
  analysis:
    name: "Static Analysis"
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Setup dart
        uses: dart-lang/setup-dart@v1
      
      - name: Install dependencies
        run: dart pub get
      
      - name: Run analysis
        run: dart analyze
  
  test:
    name: "Run Tests"
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Setup dart
        uses: dart-lang/setup-dart@v1
      
      - name: Install dependencies
        run: dart pub get
      
      - name: Generate full coverage test
        run: dart run full_coverage
      
      - name: Run tests
        run: dart run coverage:test_with_coverage
      
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/lcov.info
